services:
  backend:
    build: ./back-photo-search
    ports:
      - "5000:5000"
    volumes:
      - ./back-photo-search:/app

  frontend:
    build: ./front-photo-search
    ports:
      - "3000:3000"
    volumes:
      - ./front-photo-search:/app:cached
